### ISSUE TITLE
Feature: Stats Tracking: Enhancement

### ISSUE THREAD

**Issue by morgosus** [morgosus/archon#8]
- [ ] Track primary goal or selected goal
- [x] Track daily goal
- [x] Track weekly goal
